### PR TITLE
bhnt 75 add hacks and update title

### PR DESCRIPTION
**Pull request by lucasrangit**
I'm missing details for the winner.

### CODE REVIEW

**Comment by lucasrangit** [comment]
@vog did you happen to catch the repo or name of the winning hack?

**Comment by vog** [comment]
No, unfortunately I didn't. Do we have an means to contact the presenter, e.g. via Meetup?

**Comment by lucasrangit** [comment]
I checked but did not recognize the user.

**Comment by vog** [comment]
I had something different in mind. ;-) I wasn't thinking of searching him on Meetup, I was thinking of writing a message on Meetup to all participants kindly asking the winner to contact you.

**Comment by lucasrangit** [comment]
> I had something different in mind. ;-) I wasn't thinking of searching him on Meetup, I was thinking of writing a message on Meetup to all participants kindly asking the winner to contact you.

Haha, ok right. I posted a message, no reply in 7 days.

Shall we just merge this as is?

**Comment by vog** [comment]
Yes, let's merge it. Next meetup he'll either have to defend or hand over the trophy. If everything else fails, we can use this opportunity to ask him again.

**Pull request merged**
