### PR TITLE
Lockdown slides 2

### PR DESCRIPTION
**Pull request by ligi**

### CODE REVIEW

**Comment by lucasrangit** [comment]
Did my twitter embed code not work for you? I like using it since it links to the tweet and reflects the current retweets/likes/comments .

Also, rename assets/images/079/10_years_linux.png to 30_years...

**Review by lucasrangit — APPROVED** [review]

**Comment by ligi** [comment]
unfortunately the twitter embed codes looked really shitty. No images just weirdly formatted text. Also I think it is better as images as it will not 404 in the future ..-)
Will rename the file - thanks for spotting

**Comment by lucasrangit** [comment]
I see this briefly
before
then this renders
after

Not for you?

**Comment by ligi** [comment]
I was only seeing the first version

**Comment by lucasrangit** [comment]
Hrm... doesn't behave like a CDN issue. Maybe a problem with embedding the Etherpad. I see some errors in the console that might be delaying the twitter JS code.

**Comment by ligi** [comment]
the etherpad showed though ..

**Comment by lucasrangit** [comment]
@ligi the https://berlinhackandtell.rocks/assets/images/079/30_years_linux.png image was dropped from the last commit.

**Pull request merged**
