### PR TITLE
Add BHNT 68

### PR DESCRIPTION
**Pull request by ligi**
still missing some links - but better than nothing - perhaps @lucasrangit @nolash @ChrisChinchilla @ciex @vog @fuzxxl can fill in some blanks

### CODE REVIEW

**Comment by nolash** [comment]
@ligi love.holbrook.no

**Comment by ligi** [comment]
@nolash thanks - added

**Comment by vog** [comment]
Mine is not published yet.

**Comment by ChrisChinchilla** [comment]
@ligi https://github.com/errata-ai/vale

**Pull request merged**
