### PR TITLE
Add view for single posts / templates / generated front page

### LINKED ISSUE #187: Better layout/editing: Use jekyll data sources and post layouts
Knowing jekyll's features just a bit I know we could leverage either data sources or posts to make navigation of the page and the layout a bit more user friendly. This would allow to link to "episodes" directly instead of one big list.

### PR DESCRIPTION
**Pull request by stefanhoth**
This fixes #187 by using Jekyll's posts feature.

Benefits of the new setup/layout:

- more flexible front page, e.g. could be tied into meetup or other dynamic sources if we'd like to
- each event now has their direct link
- fewer risk for errors as new posts ( = events) create a new file with a strict template (see 29178c2aceba7c8e2cf2255a30470a1f655a41e9 as an example)

Happy about feedback!

### CODE REVIEW

**Comment by vog** [comment]
@ligi What do you think?

**Comment by stefanhoth** [comment]
These are all good points @vog and this should not be the last iteration.

Maybe [Jekyll Collections](https://jekyllrb.com/docs/collections/) are the way to get us there?

**Comment by ligi** [comment]
Generally LGTM - but my mind is on another project currently so cannot look too deep - feel free to merge. Just a visual nit:
selection_189
The meetup button is way to loud and central for my taste. It is a centralized and so wants to be loud and intrusive - but should we really help it do this ?-)

**Comment by vog** [comment]
I agree that the Meetup button is a bit too strong.

Nevertheless, merging to push this forward.

**Pull request merged**
