### PR TITLE
v2 Add BHNT 65

### PR DESCRIPTION
**Pull request by lucasrangit**
Based on @ligi 's PR #232 (with commits). Don't think I can push to that branch since it's in a fork.

Only missing the Qdolphin browser project link.

### CODE REVIEW

**Comment by ligi** [comment]
Dam - I screwed up now - thought it is OK to merge mine first and then yours on top - but got a conflict - did not see the changes - thought you just added the rest. Can you please rebase so I can merge it?

**Comment by lucasrangit** [comment]
@ligi this PR doesn't show any conflicts here on github. I did just add the rest. You'll see the commits from you are the same as from your PR.

image

**Comment by ligi** [comment]
I am seeing this:

selection_211

and can't currently really care for it as I need to prepare for a journey

**Comment by lucasrangit** [comment]
I don't understand why we saw different results. I'll ask GitHub support. Thanks for taking the time to merge. Have a safe journey!

**Comment by lucasrangit** [comment]
> I don't understand why we saw different results. I'll ask GitHub support.

I got answer from GitHub Support. Very cool!

_The Conflict Resolution check you see on your side is for a standard Merge Commit. The owner of the repository selected the Rebase and Merge option. There's some additional checks in place when Rebase and Merge is chosen as the Merge Strategy for a Pull Request. This is the reason the owner is seeing conflicts that you haven't seen. This is expected behavior for now but we'll pass your feedback onto the team to consider._

**Pull request merged**
